services:
  db:
    image: postgres:15
    container_name: transport-db
    environment:
      POSTGRES_DB: transport
      POSTGRES_USER: transport_user
      POSTGRES_PASSWORD: transport_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transport-server
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/transport
      SPRING_DATASOURCE_USERNAME: transport_user
      SPRING_DATASOURCE_PASSWORD: transport_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped

volumes:
  pgdata: