services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transport-server
    depends_on:
    - db
    environment:
      SPRING_DATASOURCE_PASSWORD: transport_pass
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/transport
      SPRING_DATASOURCE_USERNAME: transport_user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    labels:
    - com.yourdomain.project.id=68948a8f220d8a108615f9fe
    ports:
    - '8080'
    - '9090'
    restart: unless-stopped
  db:
    container_name: transport-db
    environment:
      POSTGRES_DB: transport
      POSTGRES_PASSWORD: transport_pass
      POSTGRES_USER: transport_user
    image: postgres:15
    labels:
    - com.yourdomain.project.id=68948a8f220d8a108615f9fe
    ports:
    - '5432'
    volumes:
    - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: null
