name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SPRING_PROFILES_ACTIVE: "ci"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ENVIRONMENT SETUP
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # DEPENDENCY CACHING
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    # LINTING STAGE
    - name: Run Checkstyle
      run: ./gradlew checkstyleMain
      continue-on-error: false

    # BUILD STAGE
    - name: Build project
      run: ./gradlew build -x test
      continue-on-error: false

    # TEST STAGE
    - name: Run tests
      run: ./gradlew test
      continue-on-error: false

    # BUILD DOCKER IMAGE
    - name: Build Docker image
      run: |
        docker build -t myapp:latest .
      continue-on-error: false