name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ENVIRONMENT SETUP
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # DEPENDENCY CACHING
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      # LINTING STAGE
      - name: Run Checkstyle
        run: ./gradlew checkstyle
        # QUALITY GATE: Fails on style violations

      # BUILD STAGE
      - name: Build project
        run: ./gradlew clean build
        # QUALITY GATE: Fails on compilation errors

      # TEST STAGE
      - name: Run tests
        run: ./gradlew test
        # QUALITY GATE: Fails on test failures

      # ADDITIONAL STEPS BASED ON SECRETS
      - name: Deploy to Cloud Provider
        if: secrets.AZURE_SECRET_KEY != ''
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-app'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_SECRET_KEY }}
          package: '.'
        env:
          NODE_ENV: 'production'
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}