name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ENVIRONMENT SETUP
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # DEPENDENCY CACHING
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    # LINTING STAGE
    - name: Run Checkstyle
      run: ./gradlew checkstyleMain
      # QUALITY GATE: Fails on style violations

    # BUILD STAGE
    - name: Build Java project
      run: ./gradlew clean build
      # QUALITY GATE: Fails on compilation errors

    # TEST STAGE
    - name: Run Java tests
      run: ./gradlew test
      # QUALITY GATE: Fails on test failures

    - name: Run Python tests
      run: pytest
      # QUALITY GATE: Fails on test failures

    # BUILD DOCKER IMAGE
    - name: Build Docker image
      run: docker build -t your-image-name .
      # Deploy Docker image after successful build and tests
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        FASTAPI_SECRET_KEY: ${{ secrets.FASTAPI_SECRET_KEY }}