name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ENVIRONMENT SETUP
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # DEPENDENCY CACHING
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    # LINTING STAGE
    - name: Run Checkstyle
      run: ./gradlew checkstyleMain
      continue-on-error: false

    # BUILD STAGE
    - name: Build project
      run: ./gradlew clean build
      continue-on-error: false

    # TEST STAGE
    - name: Run tests
      run: ./gradlew test
      continue-on-error: false

    # RUN SPECIFIC BUILD FOR SERVER JAR
    - name: BootJar
      run: ./gradlew :server:bootJar
      continue-on-error: false