name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Run Linter
        run: ./gradlew checkstyleMain
        # QUALITY GATE: Fails on style violations

      - name: Build project
        run: ./gradlew clean build
        # QUALITY GATE: Fails on compilation errors

      - name: Run tests
        run: ./gradlew test
        # QUALITY GATE: Fails on test failures

      - name: Build Docker image
        run: |
          docker build -t transport-server .
          # Build Docker image for deployment

      - name: Push Docker image
        run: |
          echo "${{ secrets.AZURE_SECRET_KEY }}" | docker login <your-docker-registry> --username <your-username> --password-stdin
          docker push <your-docker-registry>/transport-server
          # Push Docker image to registry for deployment